<x-catalogo-list>
    @slot('tituloTabla',$tituloTabla)
    @slot('items',$items)
    @slot('user',$user)
    @slot('editItem',$editItem)
    @slot('removeItem',$removeItem)
    @slot('Tabla')
        @include('share.Catalogos.Alumnos.alumnos_list')
    @endslot
</x-catalogo-list>
